name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # --- START: Explicit Hugo Build Steps (Gold Standard) ---
      # 1. Install Hugo using a dedicated action
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # 2. Run the Hugo build command, creating the 'public' folder
      - name: Build Hugo Site
        run: hugo --minify
      # --- END: Explicit Hugo Build Steps ---
        
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_SAND_025958810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path (Your project root)
          api_location: "" # Api source code path - optional
          
          # CRITICAL FIX: Skip the internal Oryx build step since we already ran 'hugo --minify'
          skip_app_build: true 
          
          # CRITICAL FIX: Use app_artifact_location to reliably point to the 'public' folder
          app_artifact_location: "public"
